logging:
  level:
    org.springframework.web: DEBUG
    com.f.sw: DEBUG
server:
  port: 9001
#  port: 80
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sw?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 23456789
#    data-username: root
#    data-password: 23456789
#    data: classpath:import.sql
#    sql-script-encoding: utf-8
#    initialization-mode: always
  cache:
    ehcache:
      config: classpath:conf/ehcache.xml
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc.static-path-pattern: /**
  servlet.multipart.max-file-size: 10Mb
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
#web.upload-path: /Users/fei/Downloads
web:
  upload-path: /home/sw/upload
